services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: employee-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MyPassword@123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - employee-network

  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmployeeDb;User Id=sa;Password=MyPassword@123;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - employee-network

  employee-ui-ts:
    build:
      context: ../employee-ui-ts
      dockerfile: Dockerfile
    container_name: employee-ui-ts
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/Employee
    depends_on:
      - employee-api
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge

volumes:
  sqlserver_data: